services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-prismai-bot
    restart: always
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
